version: '3'
services:
  backend:
    image: backend:latest
    ports:
      - "9000:9000"
    container_name: backend
    networks:
      - mastermind
  frontend:
    image: frontend:latest
    ports:
      - "8080:80"
    container_name: frontend
    networks:
      - mastermind

networks:
  mastermind:
    driver: gateway
